export const CREATE_SUBSCRIBER = "CREATE_SUBSCRIBER";
export const CREATE_SUBSCRIBER_SUCCESS = "CREATE_SUBSCRIBER_SUCCESS";
export const CREATE_SUBSCRIBER_ERROR = "CREATE_SUBSCRIBER_ERROR";

export const FETCH_SUBSCRIBER = "FETCH_SUBSCRIBER";
export const FETCH_SUBSCRIBER_SUCCESS = "FETCH_SUBSCRIBER_SUCCESS";
export const FETCH_SUBSCRIBER_ERROR = "FETCH_SUBSCRIBER_ERROR";

export const FETCHING_DATA = 'FETCHING_DATA';
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS';
export const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE';

